# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba4db235eed4d4bf1c76987e3a720a51764422e34c26510a364fa984f1d658b0606168070d0b946d753de0583fc9113c754e1c77347b8d65dc7d1f7f63c567b5

test:
  secret_key_base: 43dc6f8598a3424a63cf2df001e159156b81f27e437a4b649adc4fa6f81b02349e9effcd0265bcc54a8bb44164b11dde4eda774623e2f21089ea9cefc1e701bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
